apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  namespace: kafka-monitor
  name: kafka-monitor
  labels:
    app: kafka-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-monitor
  template:
    metadata:
      labels:
        app: kafka-monitor
    spec:
      containers:
      - name: kafka-monitor
        image: danielcoman/kafka-monitor:latest
        imagePullPolicy: Always
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: "km"
        volumeMounts:
          - name: kafka-monitor-volume
            mountPath: /kafka-monitor/config/kafka-monitor.properties
            subPath: kafka-monitor.properties
          - name: log4j-volume
            mountPath: /kafka-monitor/config/log4j.properties
            subPath: log4j.properties
          - name: multi-cluster-monitor-volume
            mountPath: /kafka-monitor/config/multi-cluster-monitor.properties
            subPath: multi-cluster-monitor.properties
        resources:
          requests:
            cpu: 50m
            memory: 250Mi
          # limits:
          #   memory: 500Mi
      volumes:
        - name: kafka-monitor-volume
          configMap:
            name: kafka-monitor-volume
        - name: log4j-volume
          configMap:
            name: log4j-volume
        - name: multi-cluster-monitor-volume
          configMap:
            name: multi-cluster-monitor-volume
